name = "fexample"
version = "0.1.0"
license = "MIT"
author = "Salvador Eduardo Brandolín"
maintainer = "salvadorebrandolin@unc.edu.ar"
copyright = "Copyright 2024, Salvador Eduardo Brandolín"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

